services:
  web-app:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DatabaseProvider=PostgreSQL
      - ConnectionStrings__PostgresConnection=Host=postgres-db;Database=panjeredb;Username=postgres;Password=password
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=panjeredb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
